import path from 'path';
import fs from 'fs';
import { v4 as uuidv4 } from 'uuid';
import JSZip from 'jszip';
import { dbGet, dbRun } from '../db.js';
import { spawnClaude } from './claudeCli.js';
import { getSkill, buildSystemPrompt } from '../skills/loader.js';
import { getSandboxPath } from './sandbox.js';
import { config } from '../config.js';
import { snapshotExistingFiles } from './fileManager.js';
import type { DocumentBlocksRecord, DocumentBlock, GeneratedFile } from '../types.js';

// 強茂 (PANJIT) decks are generated by pptx-gen with the PANJIT brand kit; the
// rebuild reuses that same flow, nudged by this hint so the agent re-applies the
// brand frame instead of a generic theme.
const PANJIT_REBUILD_HINT = '本簡報使用「強茂官方企業範本」。請依 SKILL 的「強茂官方範本模式」改用 PANJIT brand kit（panjit_brand.cjs）重建：保留品牌框架（封面電路圖、logo、品牌藍、頁尾頁碼），框架不變，框內內容（圖表/卡片/版面）可重新設計得更精美。';

export type AgentRebuildEvent =
  | { type: 'started' }
  | { type: 'agent_text'; data: string }
  | { type: 'agent_tool'; data: string }
  | { type: 'file_ready'; data: { file: GeneratedFile } }
  | { type: 'blocks_updated'; data: { blocks: DocumentBlock[] } }
  | { type: 'done'; data: { file: GeneratedFile; blocks: DocumentBlock[] } }
  | { type: 'error'; data: string };

/**
 * Rebuild a generated file using the pptx-gen worker agent (same quality as left-side chat).
 *
 * Flow:
 * 1. Read current block data from DB → write slides.json to agent directory
 * 2. Spawn pptx-gen worker with full SKILL.md system prompt
 * 3. Worker writes a custom pptxgenjs script + runs it → high-quality PPT
 * 4. Worker also writes updated slides.json for the editor
 * 5. We collect the output file, update DB, and re-capture blocks
 */
export async function agentRebuild(
  fileId: string,
  userId: string,
  emit?: (event: AgentRebuildEvent) => void,
  instruction?: string,
): Promise<{ file: GeneratedFile; blocks: DocumentBlock[] } | null> {
  const send = emit || (() => {});

  // ── 1. Load records ──
  const blockRecord = await dbGet<DocumentBlocksRecord>(
    'SELECT * FROM document_blocks WHERE file_id = ? AND user_id = ?',
    fileId, userId,
  );
  if (!blockRecord) {
    send({ type: 'error', data: 'Block record not found' });
    return null;
  }

  const fileRecord = await dbGet<GeneratedFile>(
    'SELECT * FROM generated_files WHERE id = ? AND user_id = ?',
    fileId, userId,
  );
  if (!fileRecord) {
    send({ type: 'error', data: 'File record not found' });
    return null;
  }

  const blocks: DocumentBlock[] = JSON.parse(blockRecord.blocks);
  const meta = blockRecord.doc_meta ? JSON.parse(blockRecord.doc_meta) : {};
  const docType = blockRecord.doc_type;

  // Only pptx is supported for agent rebuild
  if (docType !== 'pptx') {
    send({ type: 'error', data: `Agent rebuild not supported for doc_type: ${docType}` });
    return null;
  }

  // ── 2. Prepare agent directory ──
  const sandboxPath = getSandboxPath(userId, blockRecord.conversation_id);
  const agentDir = path.join(sandboxPath, '_agents', 'pptx-gen');
  fs.mkdirSync(agentDir, { recursive: true });

  // Reconstruct slides.json from block data
  const slidesJson = {
    ...meta,
    slides: blocks.sort((a, b) => a.order - b.order).map(b => ({
      type: b.type,
      ...b.data,
    })),
  };
  const slidesJsonPath = path.join(agentDir, 'slides.json');
  fs.writeFileSync(slidesJsonPath, JSON.stringify(slidesJson, null, 2), 'utf-8');

  console.log(`[AgentRebuilder] Prepared slides.json: ${blocks.length} slides, style=${meta.style || 'default'}`);

  const isPanjit = meta.style === 'panjit';

  // ── 3. Load pptx-gen skill ──
  const skill = getSkill('pptx-gen');
  if (!skill) {
    send({ type: 'error', data: 'pptx-gen skill not found' });
    return null;
  }
  const systemPrompt = buildSystemPrompt(skill, config.generatorsDir);

  // ── 4. Construct message ──
  const slidesSummary = blocks
    .sort((a, b) => a.order - b.order)
    .map((b, i) => {
      const title = (b.data as any).title || (b.data as any).quote || '';
      return `  #${i + 1} [${b.type}] ${title}`;
    })
    .join('\n');

  const message = [
    '你需要根據目前的投影片資料重新產生一份高品質的 PowerPoint 簡報。',
    '我已經把投影片資料放在 slides.json，請先讀取它。',
    '',
    '## 簡報概要',
    `標題: ${meta.title || 'Untitled'}`,
    `風格: ${meta.style || 'corporate'}`,
    `頁數: ${blocks.length}`,
    '',
    '投影片結構:',
    slidesSummary,
    '',
    '## 要求',
    '1. 讀取 slides.json 的完整資料',
    '2. 使用 pptxgenjs 撰寫一個自訂腳本來產生整份簡報',
    '3. **嚴格保持所有投影片的文字內容不變**（標題、副標題、要點、統計數據、引言等）',
    '4. 封面頁要有創意設計（使用色塊、幾何元素）',
    '5. 內容頁保持專業一致的風格',
    '6. 如果投影片資料有指定顏色樣式欄位（backgroundColor、accentColor 等），務必使用這些顏色',
    '7. 產生 output.pptx 和更新的 slides.json',
    ...(isPanjit ? ['', '## 強茂範本（最優先）', PANJIT_REBUILD_HINT] : []),
    ...(instruction ? [
      '',
      '## 整份風格調整要求（最優先）',
      `使用者希望調整整份簡報的風格：${instruction}`,
      '請在**完全保留所有文字內容、數據、頁數與結構**的前提下，把**所有投影片**統一改成這個新風格（配色、視覺元素、字體調性一致），讓整份簡報風格協調一致。只改外觀，不改文字內容。',
    ] : []),
    '',
    '請開始作業。',
  ].join('\n');

  send({ type: 'started' });

  // ── 5. Spawn pptx-gen worker ──
  return new Promise((resolve) => {
    let resolved = false;
    let agentText = '';

    const { emitter, abort } = spawnClaude(message, systemPrompt, {
      userId,
      conversationId: blockRecord.conversation_id,
      role: 'worker',
      skillId: 'pptx-gen',
      sandboxSubdir: '_agents/pptx-gen',
    });

    // Timeout: 5 minutes for rebuild
    const timeout = setTimeout(() => {
      if (resolved) return;
      console.warn('[AgentRebuilder] Agent timed out after 5 minutes');
      abort();
      resolved = true;
      send({ type: 'error', data: 'Agent rebuild timed out' });
      resolve(null);
    }, 300_000);

    emitter.on('event', async (event: any) => {
      if (resolved) return;

      if (event.type === 'text') {
        agentText += event.data;
        send({ type: 'agent_text', data: event.data });
      } else if (event.type === 'tool_activity') {
        send({ type: 'agent_tool', data: event.data });
      } else if (event.type === 'error') {
        console.error('[AgentRebuilder] Agent error:', event.data);
        clearTimeout(timeout);
        resolved = true;
        send({ type: 'error', data: String(event.data) });
        resolve(null);
      } else if (event.type === 'done') {
        clearTimeout(timeout);

        try {
          // ── 6. Find generated PPTX ──
          const pptxFiles = fs.readdirSync(agentDir)
            .filter(f => f.endsWith('.pptx') && !f.includes('.v'))
            .sort((a, b) => {
              // Prefer output.pptx, then newest file
              if (a === 'output.pptx') return -1;
              if (b === 'output.pptx') return 1;
              const sa = fs.statSync(path.join(agentDir, a));
              const sb = fs.statSync(path.join(agentDir, b));
              return sb.mtimeMs - sa.mtimeMs;
            });

          if (pptxFiles.length === 0) {
            throw new Error('Agent did not generate a PPTX file');
          }

          const generatedPptx = path.join(agentDir, pptxFiles[0]);
          const originalFilePath = path.join(config.workspaceRoot, fileRecord.file_path);

          // Copy to original file location
          fs.mkdirSync(path.dirname(originalFilePath), { recursive: true });
          fs.copyFileSync(generatedPptx, originalFilePath);
          console.log(`[AgentRebuilder] Copied ${pptxFiles[0]} → ${fileRecord.file_path}`);

          // Update file size in DB
          const newSize = fs.statSync(originalFilePath).size;
          await dbRun(
            'UPDATE generated_files SET file_size = ?, created_at = CURRENT_TIMESTAMP WHERE id = ?',
            newSize, fileId,
          );

          // Invalidate preview cache
          invalidateCache(originalFilePath, fileRecord, sandboxPath);

          // ── 7. Re-capture blocks from new slides.json ──
          let newBlocks = blocks; // Fallback: keep existing blocks
          const newSlidesJson = path.join(agentDir, 'slides.json');
          if (fs.existsSync(newSlidesJson)) {
            try {
              const raw = JSON.parse(fs.readFileSync(newSlidesJson, 'utf-8'));
              const slidesArr = raw.slides || raw.sections || raw.sheets || [];
              if (Array.isArray(slidesArr) && slidesArr.length > 0) {
                newBlocks = slidesArr.map((slide: any, i: number) => ({
                  id: blocks[i]?.id || uuidv4(), // Preserve existing IDs where possible
                  type: slide.type || 'content',
                  order: i,
                  data: slide,
                  status: 'idle',
                }));

                // Update meta if changed
                const newMeta = { ...raw };
                delete newMeta.slides;
                delete newMeta.sections;
                delete newMeta.sheets;

                await dbRun(
                  'UPDATE document_blocks SET blocks = ?, doc_meta = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?',
                  JSON.stringify(newBlocks), JSON.stringify(newMeta), blockRecord.id,
                );
                console.log(`[AgentRebuilder] Re-captured ${newBlocks.length} blocks from agent's slides.json`);
              }
            } catch (err) {
              console.warn('[AgentRebuilder] Failed to parse agent slides.json, keeping existing blocks:', err);
            }
          }

          // Fetch updated file record
          const updatedFile = await dbGet<GeneratedFile>(
            'SELECT * FROM generated_files WHERE id = ?', fileId,
          );
          if (!updatedFile) throw new Error('File record vanished');

          send({ type: 'file_ready', data: { file: updatedFile } });
          send({ type: 'blocks_updated', data: { blocks: newBlocks } });
          send({ type: 'done', data: { file: updatedFile, blocks: newBlocks } });
          resolved = true;
          resolve({ file: updatedFile, blocks: newBlocks });

        } catch (err: any) {
          console.error('[AgentRebuilder] Post-agent processing failed:', err);
          send({ type: 'error', data: err.message || 'Post-processing failed' });
          resolved = true;
          resolve(null);
        }
      }
    });
  });
}

/**
 * Rebuild a SINGLE slide using the pptx-gen worker agent, then splice the
 * generated slide into the original PPTX. All other slides stay untouched.
 *
 * Flow:
 * 1. Write slide data to agent dir as slide-rebuild.json
 * 2. Spawn pptx-gen worker: "generate only this 1 slide"
 * 3. Worker produces a 1-slide PPTX with full creative quality
 * 4. Extract slide XML from generated PPTX
 * 5. Splice into original PPTX at the correct position
 */
export async function agentRebuildSlide(
  fileId: string,
  userId: string,
  slideIndex: number,
  slideData: Record<string, unknown>,
  docMeta: Record<string, unknown>,
  allBlocks: DocumentBlock[],
  emit?: (event: AgentRebuildEvent) => void,
  instruction?: string,
): Promise<GeneratedFile | null> {
  const send = emit || (() => {});

  const fileRecord = await dbGet<GeneratedFile>(
    'SELECT * FROM generated_files WHERE id = ? AND user_id = ?',
    fileId, userId,
  );
  if (!fileRecord) { send({ type: 'error', data: 'File not found' }); return null; }

  const blockRecord = await dbGet<DocumentBlocksRecord>(
    'SELECT * FROM document_blocks WHERE file_id = ? AND user_id = ?',
    fileId, userId,
  );
  if (!blockRecord) { send({ type: 'error', data: 'Block record not found' }); return null; }

  const sandboxPath = getSandboxPath(userId, blockRecord.conversation_id);
  const agentDir = path.join(sandboxPath, '_agents', 'pptx-gen');
  fs.mkdirSync(agentDir, { recursive: true });

  const isPanjit = docMeta.style === 'panjit';

  // Write the single slide data for the agent to read
  const slideJson = { type: slideData.type, ...slideData };
  const slideJsonPath = path.join(agentDir, 'slide-rebuild.json');
  fs.writeFileSync(slideJsonPath, JSON.stringify(slideJson, null, 2), 'utf-8');

  // Load pptx-gen skill
  const skill = getSkill('pptx-gen');
  if (!skill) { send({ type: 'error', data: 'pptx-gen skill not found' }); return null; }
  const systemPrompt = buildSystemPrompt(skill, config.generatorsDir);

  // Build surrounding context so the worker knows the presentation theme
  const slidesSummary = allBlocks
    .sort((a, b) => a.order - b.order)
    .map((b, i) => {
      const title = (b.data as any).title || (b.data as any).quote || '';
      const marker = i === slideIndex ? ' ← 要修改的投影片' : '';
      return `  #${i + 1} [${b.type}] ${title}${marker}`;
    })
    .join('\n');

  const message = [
    `你需要重新產生簡報中的**第 ${slideIndex + 1} 頁**投影片（僅此一頁）。`,
    `我已經把該頁的資料放在 slide-rebuild.json，請先讀取它。`,
    '',
    '## 簡報背景',
    `標題: ${docMeta.title || 'Untitled'}`,
    `風格: ${docMeta.style || 'corporate'}`,
    `總頁數: ${allBlocks.length}`,
    '',
    '投影片結構:',
    slidesSummary,
    '',
    '## 要求',
    '1. 讀取 slide-rebuild.json 的資料',
    '2. 使用 pptxgenjs 撰寫一個腳本，**只產生這一頁**投影片',
    '3. **嚴格保持投影片的文字內容不變**（標題、副標題、要點、統計數據等）',
    '4. **圖表類型務必依照資料**：每個圖表的 `kind`（或 `type`）欄位是什麼，就畫成那種圖表——',
    '   `bar`=直條圖、`line`=折線圖、`pie`=圓餅圖、`donut`=環形圖、`area`=區域圖。',
    '   例如 `kind:"bar"` 一定要畫成直條圖，**絕對不可**因為它原本是環形圖就還是畫環形圖。沿用資料裡的 labels／values，不要改數字。',
    '   若有多個圖表（`charts` 陣列），每個都各自依其 `kind` 作畫。',
    '5. **版面完整、不可跑版**：所有元素都要在投影片邊界內，彼此**不可重疊**、要留足夠間距。',
    '   若該頁是 KPI 卡片＋圖表的組合，維持原本分區（如：卡片在上、圖表在下並排），不要讓圖表壓到卡片或文字。',
    `6. 如果是第 1 頁（封面頁），設計要有創意（色塊、幾何元素）`,
    `7. 如果是內容頁，保持專業風格，搭配 accent bar、footer 等元素`,
    '8. 如果資料有指定顏色欄位（backgroundColor、accentColor 等），**務必使用這些顏色作為整頁配色**',
    '9. 輸出檔名為 slide-output.pptx（僅 1 頁）',
    '10. 不需要產生 slides.json',
    ...(isPanjit ? ['', '## 強茂範本（最優先）', PANJIT_REBUILD_HINT, '這一頁也必須用 B.content(pptx, 標題, 頁碼) 畫品牌框，內容畫在 B.AREA 內。'] : []),
    ...(instruction ? [
      '',
      '## 使用者的具體要求（最優先）',
      instruction,
      '請依此要求調整這一頁。若是排版／版面問題（跑版、重疊、對齊、間距），務必**重新排版**，讓所有元素對齊整齊、彼此不重疊、不超出邊界。',
    ] : []),
    '',
    '請開始作業。',
  ].join('\n');

  send({ type: 'started' });

  return new Promise((resolve) => {
    let resolved = false;

    const { emitter, abort } = spawnClaude(message, systemPrompt, {
      userId,
      conversationId: blockRecord.conversation_id,
      role: 'worker',
      skillId: 'pptx-gen',
      sandboxSubdir: '_agents/pptx-gen',
    });

    const timeout = setTimeout(() => {
      if (resolved) return;
      console.warn('[AgentRebuilder] Single-slide agent timed out');
      abort();
      resolved = true;
      send({ type: 'error', data: 'Agent timed out' });
      resolve(null);
    }, 300_000);

    emitter.on('event', async (event: any) => {
      if (resolved) return;

      if (event.type === 'text') {
        send({ type: 'agent_text', data: event.data });
      } else if (event.type === 'tool_activity') {
        send({ type: 'agent_tool', data: event.data });
      } else if (event.type === 'error') {
        clearTimeout(timeout);
        resolved = true;
        send({ type: 'error', data: String(event.data) });
        resolve(null);
      } else if (event.type === 'done') {
        clearTimeout(timeout);

        try {
          // Find the 1-slide PPTX the agent generated
          const pptxFiles = fs.readdirSync(agentDir)
            .filter(f => f.endsWith('.pptx') && !f.includes('.v'))
            .sort((a, b) => {
              if (a === 'slide-output.pptx') return -1;
              if (b === 'slide-output.pptx') return 1;
              const sa = fs.statSync(path.join(agentDir, a));
              const sb = fs.statSync(path.join(agentDir, b));
              return sb.mtimeMs - sa.mtimeMs;
            });

          if (pptxFiles.length === 0) throw new Error('Agent did not generate a PPTX file');

          const generatedPptx = path.join(agentDir, pptxFiles[0]);
          const originalFilePath = path.join(config.workspaceRoot, fileRecord.file_path);

          // ── Splice: extract slide from generated PPTX → insert into original ──
          const genData = fs.readFileSync(generatedPptx);
          const genZip = await JSZip.loadAsync(genData);

          // Find generated slide (could be slide1.xml or the first slide found)
          const genSlideFile = Object.keys(genZip.files)
            .filter(p => /^ppt\/slides\/slide\d+\.xml$/.test(p))
            .sort()[0];
          if (!genSlideFile) throw new Error('No slide XML in generated PPTX');

          const newSlideXml = await genZip.file(genSlideFile)!.async('text');

          // Load original PPTX
          const origData = fs.readFileSync(originalFilePath);
          const origZip = await JSZip.loadAsync(origData);

          // Find and sort original slide files
          const origSlideFiles: string[] = [];
          origZip.forEach((p) => {
            if (/^ppt\/slides\/slide\d+\.xml$/.test(p)) origSlideFiles.push(p);
          });
          origSlideFiles.sort((a, b) => {
            const na = parseInt(a.match(/slide(\d+)/)?.[1] || '0');
            const nb = parseInt(b.match(/slide(\d+)/)?.[1] || '0');
            return na - nb;
          });

          if (slideIndex >= origSlideFiles.length) {
            throw new Error(`Slide index ${slideIndex} out of range (${origSlideFiles.length} slides)`);
          }

          // Replace target slide XML
          const targetFile = origSlideFiles[slideIndex];
          origZip.file(targetFile, newSlideXml);
          console.log(`[AgentRebuilder] Spliced agent slide into ${targetFile}`);

          // Write updated PPTX
          const output = await origZip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });
          fs.writeFileSync(originalFilePath, output);

          // Update file size
          const newSize = fs.statSync(originalFilePath).size;
          await dbRun(
            'UPDATE generated_files SET file_size = ?, created_at = CURRENT_TIMESTAMP WHERE id = ?',
            newSize, fileId,
          );

          // Invalidate preview cache
          invalidateCache(originalFilePath, fileRecord, sandboxPath);

          // Cleanup temp file
          try { fs.unlinkSync(path.join(agentDir, 'slide-rebuild.json')); } catch {}

          const updatedFile = await dbGet<GeneratedFile>(
            'SELECT * FROM generated_files WHERE id = ?', fileId,
          );
          if (!updatedFile) throw new Error('File record vanished');

          console.log(`[AgentRebuilder] Single-slide rebuild done: slide ${slideIndex + 1} (${newSize} bytes)`);
          send({ type: 'done', data: { file: updatedFile, blocks: allBlocks } });
          resolved = true;
          resolve(updatedFile);

        } catch (err: any) {
          console.error('[AgentRebuilder] Single-slide post-processing failed:', err);
          send({ type: 'error', data: err.message || 'Post-processing failed' });
          resolved = true;
          resolve(null);
        }
      }
    });
  });
}

/** Invalidate preview cache in both the sandbox root and the file's directory */
function invalidateCache(
  filePath: string,
  fileRecord: GeneratedFile,
  sandboxPath: string,
) {
  const dir = path.dirname(filePath);
  const basename = path.basename(fileRecord.filename, path.extname(fileRecord.filename));

  for (const cacheDir of new Set([dir, sandboxPath])) {
    const cachedPdf = path.join(cacheDir, '.preview-cache', `${basename}.pdf`);
    if (fs.existsSync(cachedPdf)) {
      try {
        fs.unlinkSync(cachedPdf);
        console.log(`[AgentRebuilder] Cleared preview cache: ${cachedPdf}`);
      } catch {}
    }
  }
}

// ---------------------------------------------------------------------------
// Unified deck edit — same flow as the left-side chat
// ---------------------------------------------------------------------------

/**
 * Edit a PPTX by RESUMING the conversation's pptx-gen agent session and asking
 * it to modify its own original build script (e.g. build-deck.cjs) and re-run —
 * exactly what the left-side chat does. The worker regenerates the WHOLE deck,
 * changing only what the instruction asks for, so style/layout/chart sizing stay
 * consistent with the rest of the presentation.
 *
 * This replaces the old isolated "generate just 1 slide and splice" approach,
 * which produced off-style, single-page results because it spawned a FRESH agent
 * in a different working dir with no access to the original generation script.
 *
 * Used by BOTH single-page/single-block edits and the whole-deck rebuild — the
 * only difference is the `instruction` (scoped to one page vs. the whole deck).
 *
 * The output file is overwritten in place (same fileId, same path); blocks are
 * re-captured from the agent's updated slides.json so the editor refreshes.
 */
export async function agentEditDeck(
  fileId: string,
  userId: string,
  instruction: string,
  emit?: (event: AgentRebuildEvent) => void,
): Promise<{ file: GeneratedFile; blocks: DocumentBlock[] } | null> {
  const send = emit || (() => {});

  const fileRecord = await dbGet<GeneratedFile>(
    'SELECT * FROM generated_files WHERE id = ? AND user_id = ?', fileId, userId,
  );
  if (!fileRecord) { send({ type: 'error', data: 'File not found' }); return null; }

  const blockRecord = await dbGet<DocumentBlocksRecord>(
    'SELECT * FROM document_blocks WHERE file_id = ? AND user_id = ?', fileId, userId,
  );
  if (!blockRecord) { send({ type: 'error', data: 'Block record not found' }); return null; }
  if (blockRecord.doc_type !== 'pptx') {
    send({ type: 'error', data: `agentEditDeck only supports pptx (got ${blockRecord.doc_type})` });
    return null;
  }

  const conversationId = blockRecord.conversation_id;

  // The pptx-gen worker runs in its OWN agent dir (where its build script +
  // slides.json live) and resumes its OWN persistent session — exactly how the
  // orchestrator re-dispatches a follow-up edit. Resuming that session is what
  // lets the worker re-read and modify its original build script instead of
  // improvising a fresh, off-style one.
  const sandboxPath = getSandboxPath(userId, conversationId);
  const agentDir = path.join(sandboxPath, '_agents', 'pptx-gen');
  fs.mkdirSync(agentDir, { recursive: true });
  const originalFilePath = path.join(config.workspaceRoot, fileRecord.file_path);

  const skill = getSkill('pptx-gen');
  if (!skill) { send({ type: 'error', data: 'pptx-gen skill not found' }); return null; }
  const systemPrompt = buildSystemPrompt(skill, config.generatorsDir);

  // Get-or-create the pptx-gen worker's persistent session (agent_sessions),
  // mirroring Orchestrator.getOrCreateAgentSession.
  let agentSession = await dbGet<{ session_uuid: string; initialized: number }>(
    'SELECT session_uuid, initialized FROM agent_sessions WHERE conversation_id = ? AND skill_id = ?',
    conversationId, 'pptx-gen',
  );
  if (!agentSession) {
    const fresh = uuidv4();
    await dbRun(
      'INSERT INTO agent_sessions (id, conversation_id, skill_id, session_uuid) VALUES (?, ?, ?, ?)',
      uuidv4(), conversationId, 'pptx-gen', fresh,
    );
    agentSession = { session_uuid: fresh, initialized: 0 };
  }

  // Snapshot the current file for version history before we overwrite it.
  // We deliberately keep the SAME fileId (no registerNewFiles fork).
  await snapshotExistingFiles(userId, conversationId);

  const message = [
    instruction,
    '',
    '## 執行方式（務必遵守）',
    `- 你之前已經在這個工作目錄產生過這份簡報「${fileRecord.filename}」。請**讀取並修改你先前用來產生它的 pptxgenjs 腳本**（例如 build-deck.cjs / generate.cjs 等；若真的找不到，就讀現有的 slides.json 重建一支等效腳本）。`,
    `- 改完後**重新執行腳本**，覆蓋產生「同一個檔名」的簡報:\`${fileRecord.filename}\`（不要改檔名、不要新增別的 .pptx）。`,
    '- **只變更指令要求的部分**,其餘所有頁面的文字、數據、版面、配色一律保持完全不變。',
    '- 同步更新同目錄的 `slides.json`，讓編輯器能反映這次變更。',
    '- 完成後簡短回報即可,不需冗長說明。',
  ].join('\n');

  send({ type: 'started' });

  return new Promise((resolve) => {
    let resolved = false;
    let hasRetried = false;

    const run = (sessionId: string, isResume: boolean) => {
      const { emitter, abort } = spawnClaude(message, systemPrompt, {
        userId,
        conversationId,
        sessionId,
        isResume,
        role: 'worker',
        skillId: 'pptx-gen',
        sandboxSubdir: '_agents/pptx-gen',
        customAllowedTools: skill.allowedTools,
        customDisallowedTools: skill.disallowedTools,
      });

      const timeout = setTimeout(() => {
        if (resolved) return;
        console.warn('[AgentEditDeck] Agent timed out after 5 minutes');
        abort();
        resolved = true;
        send({ type: 'error', data: 'Deck edit timed out' });
        resolve(null);
      }, 300_000);

      emitter.on('event', async (event: any) => {
        if (resolved) return;

        if (event.type === 'text') {
          send({ type: 'agent_text', data: event.data });
        } else if (event.type === 'tool_activity') {
          send({ type: 'agent_tool', data: event.data });
        } else if (event.type === 'session_id') {
          const sid = event.data as string;
          if (sid) dbRun(
            'UPDATE agent_sessions SET session_uuid = ?, initialized = 1 WHERE conversation_id = ? AND skill_id = ?',
            sid, conversationId, 'pptx-gen',
          ).catch(() => {});
        } else if (event.type === 'error') {
          // Resume can fail if the session is stale/busy — retry once with a
          // fresh session (the build script is still on disk, so the worker can
          // still read + modify it from the instruction alone).
          const errStr = String(event.data || '');
          if (isResume && !hasRetried && /Session|exit|code 1/.test(errStr)) {
            hasRetried = true;
            clearTimeout(timeout);
            console.log('[AgentEditDeck] Resume failed, retrying with fresh session');
            const fresh = uuidv4();
            await dbRun(
              'UPDATE agent_sessions SET session_uuid = ?, initialized = 0 WHERE conversation_id = ? AND skill_id = ?',
              fresh, conversationId, 'pptx-gen',
            ).catch(() => {});
            run(fresh, false);
            return;
          }
          clearTimeout(timeout);
          resolved = true;
          send({ type: 'error', data: errStr });
          resolve(null);
        } else if (event.type === 'done') {
          clearTimeout(timeout);
          try {
            // The worker wrote the edited deck in its agent dir → copy it onto the
            // registered file path (conversation root), keeping the SAME fileId.
            const pptxFiles = fs.readdirSync(agentDir)
              .filter(f => f.endsWith('.pptx') && !f.includes('.v'))
              .sort((a, b) => {
                if (a === fileRecord.filename) return -1;
                if (b === fileRecord.filename) return 1;
                if (a === 'output.pptx') return -1;
                if (b === 'output.pptx') return 1;
                return fs.statSync(path.join(agentDir, b)).mtimeMs - fs.statSync(path.join(agentDir, a)).mtimeMs;
              });
            if (pptxFiles.length === 0) throw new Error('Agent did not produce a PPTX file');

            const generatedPptx = path.join(agentDir, pptxFiles[0]);
            // The registered file_path often IS the agent-dir file itself (the
            // worker writes the deck straight into its cwd). Only copy when the
            // registered path is somewhere else (e.g. conversation root).
            if (path.resolve(generatedPptx) !== path.resolve(originalFilePath)) {
              fs.mkdirSync(path.dirname(originalFilePath), { recursive: true });
              fs.copyFileSync(generatedPptx, originalFilePath);
              console.log(`[AgentEditDeck] Copied ${pptxFiles[0]} → ${fileRecord.file_path}`);
            } else {
              console.log(`[AgentEditDeck] Edited deck in place at ${fileRecord.file_path}`);
            }

            const newSize = fs.statSync(originalFilePath).size;
            await dbRun(
              'UPDATE generated_files SET file_size = ?, created_at = CURRENT_TIMESTAMP WHERE id = ?',
              newSize, fileId,
            );
            invalidateCache(originalFilePath, fileRecord, sandboxPath);

            // Re-capture blocks from the agent's updated slides.json, UPDATING the
            // SAME document_blocks row. (captureBlocksForFile INSERTs a new row,
            // which would duplicate blocks for this unchanged fileId.) Preserve
            // existing block ids by index so the editor's selection stays stable.
            const existingBlocks: DocumentBlock[] = JSON.parse(blockRecord.blocks);
            let blocks = existingBlocks;
            const slidesJsonPath = path.join(agentDir, 'slides.json');
            if (fs.existsSync(slidesJsonPath)) {
              try {
                const raw = JSON.parse(fs.readFileSync(slidesJsonPath, 'utf-8'));
                const slidesArr = raw.slides || raw.sections || raw.sheets || [];
                if (Array.isArray(slidesArr) && slidesArr.length > 0) {
                  blocks = slidesArr.map((slide: any, i: number) => ({
                    id: existingBlocks[i]?.id || uuidv4(),
                    type: slide.type || 'content',
                    order: i,
                    data: slide,
                    status: 'idle',
                  }));
                  const newMeta = { ...raw };
                  delete newMeta.slides; delete newMeta.sections; delete newMeta.sheets;
                  await dbRun(
                    'UPDATE document_blocks SET blocks = ?, doc_meta = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?',
                    JSON.stringify(blocks), JSON.stringify(newMeta), blockRecord.id,
                  );
                }
              } catch (e) {
                console.warn('[AgentEditDeck] Failed to parse updated slides.json:', e);
              }
            }

            const updatedFile = await dbGet<GeneratedFile>('SELECT * FROM generated_files WHERE id = ?', fileId);
            if (!updatedFile) throw new Error('File record vanished');

            send({ type: 'file_ready', data: { file: updatedFile } });
            send({ type: 'blocks_updated', data: { blocks } });
            send({ type: 'done', data: { file: updatedFile, blocks } });
            resolved = true;
            resolve({ file: updatedFile, blocks });
          } catch (err: any) {
            console.error('[AgentEditDeck] Post-agent processing failed:', err);
            resolved = true;
            send({ type: 'error', data: err.message || 'Post-processing failed' });
            resolve(null);
          }
        }
      });
    };

    run(agentSession.session_uuid, agentSession.initialized === 1);
  });
}

/**
 * Regenerate ANY generated file IN PLACE by resuming its generator skill's
 * session and instructing it to fix a problem (e.g. remove fabricated data),
 * overwriting the SAME file (same id, same path).
 *
 * Format-agnostic — unlike agentRebuild/agentEditDeck (pptx-only, slides.json
 * aware), this makes no assumptions about the output type. Used by the data-
 * fidelity guard to auto-correct docx/xlsx/pdf/html in BOTH flows:
 *  - template-wizard (direct): skill ran in the BASE sandbox on the conversation
 *    session → call with no `sandboxSubdir` and the conversation session id.
 *  - orchestrated (auto): worker ran in `_agents/{skillId}` on its per-skill
 *    agent_session → pass `sandboxSubdir='_agents/{skillId}'` and that session id.
 * In both, `previous_step.md` and the output file live in that same cwd, so the
 * worker overwrites the file in place. Non-fatal: returns null on any failure so
 * the caller can fall back to flagging.
 */
export async function agentRegenerateInPlace(
  file: GeneratedFile,
  userId: string,
  conversationId: string,
  skillId: string,
  sessionId: string,
  instruction: string,
  sandboxSubdir?: string,
): Promise<GeneratedFile | null> {
  const skill = getSkill(skillId);
  if (!skill || !sessionId) return null;
  const systemPrompt = buildSystemPrompt(skill, config.generatorsDir);

  const sandboxPath = getSandboxPath(userId, conversationId);
  const originalFilePath = path.join(config.workspaceRoot, file.file_path);

  // Version-snapshot before overwriting so the original is recoverable.
  await snapshotExistingFiles(userId, conversationId);

  const message = [
    instruction,
    '',
    '## 執行方式（務必遵守）',
    `- 你剛剛在這個工作目錄產生了「${file.filename}」。請**重新產生同一個檔案**（同檔名 \`${file.filename}\`，原地覆蓋），不要新增其他檔案、不要改副檔名。`,
    '- 完整資料以工作目錄的 `previous_step.md` 為準（若存在）：請**先用 Read 讀取它**，所有名稱／數字只能來自該檔、或由其數字計算得出，不可編造。',
    '- **只移除上面指出的編造內容**，其餘真實內容、版面、風格一律保持不變。',
    '- 完成後簡短回報即可，不需冗長說明。',
  ].join('\n');

  return new Promise((resolve) => {
    let resolved = false;
    let hasRetried = false;

    const run = (sid: string, isResume: boolean) => {
      const { emitter, abort } = spawnClaude(message, systemPrompt, {
        userId,
        conversationId,
        sessionId: sid,
        isResume,
        role: 'worker',
        skillId,
        ...(sandboxSubdir ? { sandboxSubdir } : {}),
        customAllowedTools: skill.allowedTools,
        customDisallowedTools: skill.disallowedTools,
      });

      const timeout = setTimeout(() => {
        if (resolved) return;
        try { abort(); } catch { /* ignore */ }
        resolved = true;
        console.warn('[AgentRegenerate] timed out');
        resolve(null);
      }, 300_000);

      emitter.on('event', async (event: any) => {
        if (resolved) return;

        if (event.type === 'session_id') {
          const sd = event.data as string;
          if (sd) dbRun('UPDATE conversations SET session_id = ? WHERE id = ?', sd, conversationId).catch(() => {});
        } else if (event.type === 'error') {
          const errStr = String(event.data || '');
          if (isResume && !hasRetried && /Session|exit|code 1/.test(errStr)) {
            hasRetried = true;
            clearTimeout(timeout);
            run(uuidv4(), false);
            return;
          }
          clearTimeout(timeout);
          resolved = true;
          resolve(null);
        } else if (event.type === 'done') {
          clearTimeout(timeout);
          try {
            if (!fs.existsSync(originalFilePath)) { resolved = true; resolve(null); return; }
            const newSize = fs.statSync(originalFilePath).size;
            await dbRun(
              'UPDATE generated_files SET file_size = ?, created_at = CURRENT_TIMESTAMP WHERE id = ?',
              newSize, file.id,
            );
            invalidateCache(originalFilePath, file, sandboxPath);
            const updated = await dbGet<GeneratedFile>('SELECT * FROM generated_files WHERE id = ?', file.id);
            resolved = true;
            resolve(updated || null);
          } catch (e) {
            console.warn('[AgentRegenerate] post-processing failed:', e);
            resolved = true;
            resolve(null);
          }
        }
      });
    };

    run(sessionId, true);
  });
}
